#if UNITY_EDITOR
using UnityEditor;
#endif

using UnityEngine;

public class ProductionBuildingSource : MonoBehaviour {

    [SerializeField] private bool unique = false;
    [Tooltip("autogenerated")]
    [SerializeField] private int uniqueId = 0;
    [Space]
    [Inline] [SerializeField] private ProductionBuildingConfig config;
    [Inline, SerializeField] private CombatPrototypeSource combatSource;
    [Local] [SerializeField] private PhysicsObstacle dimensionsPrefab;
    [Local] [SerializeField] private RagdollObstacle physicsObstaclePrefab;
    [Local] [SerializeField] private GameObject visualsPrefab;
    [Inline] [Local] [SerializeField] private SpawnSpotSource spawnSpotSource;
    [SerializeField] SpawnVariantSource spawnVariantSource;

    private bool lastUniqueFlag;

#if UNITY_EDITOR
    private void OnValidate() {
        var changed = unique == lastUniqueFlag;
        lastUniqueFlag = unique;
        if (changed) {
            uniqueId = GUID.Generate().GetHashCode();
        }
    }
#endif

    private void Awake() {
        gameObject.SetActive(false);
    }

    public int GetUniqueId() {
        return uniqueId;
    }

    public ProductionBuildingPrototype GetPrototype() {
        return new ProductionBuildingPrototype {
            uniqueId = uniqueId,
            position = transform.position,
            rotation = transform.rotation,
            config = config,
            spawnSpot = spawnSpotSource.Get(),
            spawnVariant = spawnVariantSource.Get(),
            dimensionsPrefab = dimensionsPrefab,
            physicsObstaclePrefab = physicsObstaclePrefab,
            visualsPrefab = visualsPrefab,
            combatPrototype = combatSource.Get(),
        };
    }
}
