#if UNITY_EDITOR
using UnityEditor;
#endif

using UnityEngine;

public class ProductionBuildingSource : MonoBehaviour {

    [SerializeField] private bool unique = false;
    [Tooltip("autogenerated")]
    [SerializeField] private int uniqueId = 0;
    [Space]
    [Inline] [SerializeField] private ProductionBuildingConfig config;
    [Local] [SerializeField] private SpawnSpotSource spawnSpotSource;
    [Local] [SerializeField] private PhysicsObstacle dimensionsPrefab;
    [Local] [SerializeField] private GameObject visualsPrefab;

    private bool lastUniqueFlag;

#if UNITY_EDITOR
    private void OnValidate() {
        var changed = unique == lastUniqueFlag;
        lastUniqueFlag = unique;
        if (changed) {
            uniqueId = GUID.Generate().GetHashCode();
        }
    }
#endif

    public int GetUniqueId() {
        return uniqueId;
    }

    public ProductionBuildingPrototype GetPrototype() {
        return new ProductionBuildingPrototype {
            uniqueId = uniqueId,
            position = transform.position,
            rotation = transform.rotation,
            config = config,
            spawnSpot = spawnSpotSource.Provide(),
            dimensionsPrefab = dimensionsPrefab,
            visualsPrefab = visualsPrefab,
        };
    }
}