using UnityEditor;

using UnityEngine;

public class ProductionSpaceSource : MonoBehaviour {
    
    [SerializeField] private bool unique = false;
    [Tooltip("autogenerated")]
    [SerializeField] private int uniqueId = 0;
    [Space]
    [Inline] [SerializeField] private ProductionSpaceConfig config;
    [Local] [SerializeField] private SpawnSpotSource spawnSpotSource;

    private bool lastUniqueFlag;

    private void OnValidate() {
        var changed = unique == lastUniqueFlag;
        lastUniqueFlag = unique;
        if (changed) {
            uniqueId = GUID.Generate().GetHashCode();
        }
    }

    public int GetUniqueId() {
        return uniqueId;
    }

    public ProductionSpacePrototype GetPrototype() {
        return new ProductionSpacePrototype {
            uniqueId = uniqueId,
            config = config,
            position = transform.position,
            rotation = transform.rotation,
            spawnSpot = spawnSpotSource.Provide(), 
        };
    }
}